// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.
//
// Code generated by "github.com/DataDog/orchestrion/internal/advice/code/generator -o dot_ast.proxies.go"; DO NOT EDIT.

package code

import dst "github.com/dave/dst"

type proxyArrayType struct {
	*dst.ArrayType
	placeholders *placeholders
}

func (p *proxyArrayType) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyArrayType) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyArrayType) Len() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyArrayType) Elt() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyAssignStmt struct {
	*dst.AssignStmt
	placeholders *placeholders
}

func (p *proxyAssignStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyAssignStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyAssignStmt) Lhs() []dst.Expr { _ = "STUB: not implemented"; return nil }

func (p *proxyAssignStmt) Rhs() []dst.Expr { _ = "STUB: not implemented"; return nil }

type proxyBadDecl struct {
	*dst.BadDecl
	placeholders *placeholders
}

func (p *proxyBadDecl) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBadDecl) String() string { _ = "STUB: not implemented"; return "" }

type proxyBadExpr struct {
	*dst.BadExpr
	placeholders *placeholders
}

func (p *proxyBadExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBadExpr) String() string { _ = "STUB: not implemented"; return "" }

type proxyBadStmt struct {
	*dst.BadStmt
	placeholders *placeholders
}

func (p *proxyBadStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBadStmt) String() string { _ = "STUB: not implemented"; return "" }

type proxyBasicLit struct {
	*dst.BasicLit
	placeholders *placeholders
}

func (p *proxyBasicLit) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBasicLit) String() string { _ = "STUB: not implemented"; return "" }

type proxyBinaryExpr struct {
	*dst.BinaryExpr
	placeholders *placeholders
}

func (p *proxyBinaryExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBinaryExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBinaryExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyBinaryExpr) Y() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyBlockStmt struct {
	*dst.BlockStmt
	placeholders *placeholders
}

func (p *proxyBlockStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBlockStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBlockStmt) List() []dst.Stmt { _ = "STUB: not implemented"; return nil }

type proxyBranchStmt struct {
	*dst.BranchStmt
	placeholders *placeholders
}

func (p *proxyBranchStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBranchStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyBranchStmt) Label() *proxyIdent { _ = "STUB: not implemented"; return nil }

type proxyCallExpr struct {
	*dst.CallExpr
	placeholders *placeholders
}

func (p *proxyCallExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCallExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCallExpr) Fun() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyCallExpr) Args() []dst.Expr { _ = "STUB: not implemented"; return nil }

type proxyCaseClause struct {
	*dst.CaseClause
	placeholders *placeholders
}

func (p *proxyCaseClause) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCaseClause) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCaseClause) List() []dst.Expr { _ = "STUB: not implemented"; return nil }

func (p *proxyCaseClause) Body() []dst.Stmt { _ = "STUB: not implemented"; return nil }

type proxyChanType struct {
	*dst.ChanType
	placeholders *placeholders
}

func (p *proxyChanType) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyChanType) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyChanType) Value() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyCommClause struct {
	*dst.CommClause
	placeholders *placeholders
}

func (p *proxyCommClause) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCommClause) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCommClause) Comm() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

func (p *proxyCommClause) Body() []dst.Stmt { _ = "STUB: not implemented"; return nil }

type proxyCompositeLit struct {
	*dst.CompositeLit
	placeholders *placeholders
}

func (p *proxyCompositeLit) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCompositeLit) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyCompositeLit) Type() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyCompositeLit) Elts() []dst.Expr { _ = "STUB: not implemented"; return nil }

type proxyDeclStmt struct {
	*dst.DeclStmt
	placeholders *placeholders
}

func (p *proxyDeclStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyDeclStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyDeclStmt) Decl() dst.Decl { _ = "STUB: not implemented"; return *new(dst.Decl) }

type proxyDeferStmt struct {
	*dst.DeferStmt
	placeholders *placeholders
}

func (p *proxyDeferStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyDeferStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyDeferStmt) Call() *proxyCallExpr { _ = "STUB: not implemented"; return nil }

type proxyEllipsis struct {
	*dst.Ellipsis
	placeholders *placeholders
}

func (p *proxyEllipsis) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyEllipsis) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyEllipsis) Elt() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyEmptyStmt struct {
	*dst.EmptyStmt
	placeholders *placeholders
}

func (p *proxyEmptyStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyEmptyStmt) String() string { _ = "STUB: not implemented"; return "" }

type proxyExprStmt struct {
	*dst.ExprStmt
	placeholders *placeholders
}

func (p *proxyExprStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyExprStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyExprStmt) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyField struct {
	*dst.Field
	placeholders *placeholders
}

func (p *proxyField) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyField) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyField) Type() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyField) Tag() *proxyBasicLit { _ = "STUB: not implemented"; return nil }

type proxyFieldList struct {
	*dst.FieldList
	placeholders *placeholders
}

func (p *proxyFieldList) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFieldList) String() string { _ = "STUB: not implemented"; return "" }

type proxyFile struct {
	*dst.File
	placeholders *placeholders
}

func (p *proxyFile) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFile) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFile) Name() *proxyIdent { _ = "STUB: not implemented"; return nil }

func (p *proxyFile) Decls() []dst.Decl { _ = "STUB: not implemented"; return nil }

type proxyForStmt struct {
	*dst.ForStmt
	placeholders *placeholders
}

func (p *proxyForStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyForStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyForStmt) Init() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

func (p *proxyForStmt) Cond() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyForStmt) Post() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

func (p *proxyForStmt) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

type proxyFuncDecl struct {
	*dst.FuncDecl
	placeholders *placeholders
}

func (p *proxyFuncDecl) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFuncDecl) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFuncDecl) Recv() *proxyFieldList { _ = "STUB: not implemented"; return nil }

func (p *proxyFuncDecl) Name() *proxyIdent { _ = "STUB: not implemented"; return nil }

func (p *proxyFuncDecl) Type() *proxyFuncType { _ = "STUB: not implemented"; return nil }

func (p *proxyFuncDecl) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

type proxyFuncLit struct {
	*dst.FuncLit
	placeholders *placeholders
}

func (p *proxyFuncLit) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFuncLit) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFuncLit) Type() *proxyFuncType { _ = "STUB: not implemented"; return nil }

func (p *proxyFuncLit) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

type proxyFuncType struct {
	*dst.FuncType
	placeholders *placeholders
}

func (p *proxyFuncType) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFuncType) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyFuncType) TypeParams() *proxyFieldList { _ = "STUB: not implemented"; return nil }

func (p *proxyFuncType) Params() *proxyFieldList { _ = "STUB: not implemented"; return nil }

func (p *proxyFuncType) Results() *proxyFieldList { _ = "STUB: not implemented"; return nil }

type proxyGenDecl struct {
	*dst.GenDecl
	placeholders *placeholders
}

func (p *proxyGenDecl) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyGenDecl) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyGenDecl) Specs() []dst.Spec { _ = "STUB: not implemented"; return nil }

type proxyGoStmt struct {
	*dst.GoStmt
	placeholders *placeholders
}

func (p *proxyGoStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyGoStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyGoStmt) Call() *proxyCallExpr { _ = "STUB: not implemented"; return nil }

type proxyIdent struct {
	*dst.Ident
	placeholders *placeholders
}

func (p *proxyIdent) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIdent) String() string { _ = "STUB: not implemented"; return "" }

type proxyIfStmt struct {
	*dst.IfStmt
	placeholders *placeholders
}

func (p *proxyIfStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIfStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIfStmt) Init() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

func (p *proxyIfStmt) Cond() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyIfStmt) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

func (p *proxyIfStmt) Else() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

type proxyImportSpec struct {
	*dst.ImportSpec
	placeholders *placeholders
}

func (p *proxyImportSpec) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyImportSpec) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyImportSpec) Name() *proxyIdent { _ = "STUB: not implemented"; return nil }

func (p *proxyImportSpec) Path() *proxyBasicLit { _ = "STUB: not implemented"; return nil }

type proxyIncDecStmt struct {
	*dst.IncDecStmt
	placeholders *placeholders
}

func (p *proxyIncDecStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIncDecStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIncDecStmt) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyIndexExpr struct {
	*dst.IndexExpr
	placeholders *placeholders
}

func (p *proxyIndexExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIndexExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIndexExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyIndexExpr) Index() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyIndexListExpr struct {
	*dst.IndexListExpr
	placeholders *placeholders
}

func (p *proxyIndexListExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIndexListExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyIndexListExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyIndexListExpr) Indices() []dst.Expr { _ = "STUB: not implemented"; return nil }

type proxyInterfaceType struct {
	*dst.InterfaceType
	placeholders *placeholders
}

func (p *proxyInterfaceType) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyInterfaceType) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyInterfaceType) Methods() *proxyFieldList { _ = "STUB: not implemented"; return nil }

type proxyKeyValueExpr struct {
	*dst.KeyValueExpr
	placeholders *placeholders
}

func (p *proxyKeyValueExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyKeyValueExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyKeyValueExpr) Key() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyKeyValueExpr) Value() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyLabeledStmt struct {
	*dst.LabeledStmt
	placeholders *placeholders
}

func (p *proxyLabeledStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyLabeledStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyLabeledStmt) Label() *proxyIdent { _ = "STUB: not implemented"; return nil }

func (p *proxyLabeledStmt) Stmt() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

type proxyMapType struct {
	*dst.MapType
	placeholders *placeholders
}

func (p *proxyMapType) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyMapType) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyMapType) Key() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyMapType) Value() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyPackage struct {
	*dst.Package
	placeholders *placeholders
}

func (p *proxyPackage) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyPackage) String() string { _ = "STUB: not implemented"; return "" }

type proxyParenExpr struct {
	*dst.ParenExpr
	placeholders *placeholders
}

func (p *proxyParenExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyParenExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyParenExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyRangeStmt struct {
	*dst.RangeStmt
	placeholders *placeholders
}

func (p *proxyRangeStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyRangeStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyRangeStmt) Key() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyRangeStmt) Value() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyRangeStmt) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyRangeStmt) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

type proxyReturnStmt struct {
	*dst.ReturnStmt
	placeholders *placeholders
}

func (p *proxyReturnStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyReturnStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyReturnStmt) Results() []dst.Expr { _ = "STUB: not implemented"; return nil }

type proxySelectStmt struct {
	*dst.SelectStmt
	placeholders *placeholders
}

func (p *proxySelectStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxySelectStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxySelectStmt) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

type proxySelectorExpr struct {
	*dst.SelectorExpr
	placeholders *placeholders
}

func (p *proxySelectorExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxySelectorExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxySelectorExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxySelectorExpr) Sel() *proxyIdent { _ = "STUB: not implemented"; return nil }

type proxySendStmt struct {
	*dst.SendStmt
	placeholders *placeholders
}

func (p *proxySendStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxySendStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxySendStmt) Chan() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxySendStmt) Value() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxySliceExpr struct {
	*dst.SliceExpr
	placeholders *placeholders
}

func (p *proxySliceExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxySliceExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxySliceExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxySliceExpr) Low() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxySliceExpr) High() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxySliceExpr) Max() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyStarExpr struct {
	*dst.StarExpr
	placeholders *placeholders
}

func (p *proxyStarExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyStarExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyStarExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyStructType struct {
	*dst.StructType
	placeholders *placeholders
}

func (p *proxyStructType) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyStructType) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyStructType) Fields() *proxyFieldList { _ = "STUB: not implemented"; return nil }

type proxySwitchStmt struct {
	*dst.SwitchStmt
	placeholders *placeholders
}

func (p *proxySwitchStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxySwitchStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxySwitchStmt) Init() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

func (p *proxySwitchStmt) Tag() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxySwitchStmt) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

type proxyTypeAssertExpr struct {
	*dst.TypeAssertExpr
	placeholders *placeholders
}

func (p *proxyTypeAssertExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyTypeAssertExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyTypeAssertExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyTypeAssertExpr) Type() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyTypeSpec struct {
	*dst.TypeSpec
	placeholders *placeholders
}

func (p *proxyTypeSpec) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyTypeSpec) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyTypeSpec) Name() *proxyIdent { _ = "STUB: not implemented"; return nil }

func (p *proxyTypeSpec) TypeParams() *proxyFieldList { _ = "STUB: not implemented"; return nil }

func (p *proxyTypeSpec) Type() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyTypeSwitchStmt struct {
	*dst.TypeSwitchStmt
	placeholders *placeholders
}

func (p *proxyTypeSwitchStmt) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyTypeSwitchStmt) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyTypeSwitchStmt) Init() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

func (p *proxyTypeSwitchStmt) Assign() dst.Stmt { _ = "STUB: not implemented"; return *new(dst.Stmt) }

func (p *proxyTypeSwitchStmt) Body() *proxyBlockStmt { _ = "STUB: not implemented"; return nil }

type proxyUnaryExpr struct {
	*dst.UnaryExpr
	placeholders *placeholders
}

func (p *proxyUnaryExpr) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyUnaryExpr) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyUnaryExpr) X() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

type proxyValueSpec struct {
	*dst.ValueSpec
	placeholders *placeholders
}

func (p *proxyValueSpec) Copy() string { _ = "STUB: not implemented"; return "" }

func (p *proxyValueSpec) String() string { _ = "STUB: not implemented"; return "" }

func (p *proxyValueSpec) Type() dst.Expr { _ = "STUB: not implemented"; return *new(dst.Expr) }

func (p *proxyValueSpec) Values() []dst.Expr { _ = "STUB: not implemented"; return nil }

func newProxy[T any](node any, placeholders *placeholders) T {
	_ = "STUB: not implemented"
	return *new(T)
}
