// Unless explicitly stated otherwise all files in this repository are licensed
// under the Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2023-present Datadog, Inc.

package report

import (
	"context"
	"io"
	"io/fs"
)

// FromWorkDir reads the orchestrion files from a `go build -work` directory and creates a [Report] out of it.
func FromWorkDir(ctx context.Context, dir string) (Report, error) {
	_ = "STUB: not implemented"
	return *new(Report), nil
}

func fromWorkFS(ctx context.Context, root string, fsys fs.FS) (Report, error) {
	_ = "STUB: not implemented"
	return *new(Report), nil
}

// Sort the files by their modified path relative to the work directory.

type (
	// ModifiedFile represents a file that has been modified by Orchestrion.
	ModifiedFile struct {
		// original is the fullpath of the original file before it was modified by Orchestrion.
		// It can be already deleted in certain cases, such as when the original file was a CGo file that was not modified.
		original string

		// modified is the fullpath of the modified file that was generated by Orchestrion. It can be missing
		// if a build was made without the `-work` flag.
		modified string
	}

	// Report represents a collection of modified files that were generated by Orchestrion.
	// It implements the [fs.FS] interface, allowing it to be used as a file system rooted in "/".
	// This will open every file normally expect for files that have been modified by Orchestrion, in which case it will
	// open the modified file instead of the original file.
	Report struct {
		files []ModifiedFile
		fs    fs.FS
		root  string
	}
)

// NewModifiedFile creates a new ModifiedFile from the given file system and modified path.
// If the modified file contains a line directive, it will parse it to find the original path.
func NewModifiedFile(fsys fs.FS, modifiedPath string) (ModifiedFile, error) {
	_ = "STUB: not implemented"
	return *new(ModifiedFile), nil
}

func (m ModifiedFile) String() string { _ = "STUB: not implemented"; return "" }

// ImportPath converts the modified file path to an import path.
func (m ModifiedFile) ImportPath() string { _ = "STUB: not implemented"; return "" }

var _ fs.FS = (*Report)(nil)

func (r Report) Open(name string) (fs.File, error) {
	_ = "STUB: not implemented"
	return *new(fs.File), nil
}

var _ fs.FS = (*Report)(nil)

// WithRegexFilter filters the files in the report based on a regex pattern.
func (r Report) WithRegexFilter(regex string) (Report, error) {
	_ = "STUB: not implemented"
	return *new(Report), nil
}

// WithSpecialCasesFilter filters the files in the report to include only those that are not weaver special cases
func (r Report) WithSpecialCasesFilter() Report { _ = "STUB: not implemented"; return *new(Report) }

// Diff generates a diff between the original and modified files and writes it to the writer.
func (r Report) Diff(writer io.Writer) error {
	_ = "STUB: not implemented"

	// Check if the diff command is available, exit early if not
	return nil
}

func (r Report) diff(writer io.Writer, file ModifiedFile) error {
	_ = "STUB: not implemented"
	// If originalPath does not exists, it means that we have cgo files in there, just skip it
	return nil
}

// When adding options, always make sure this is supported on all platforms.

// Use the unified context diff format
// Try harder to minimize the diff
// Treat all files as text
// Change the output to colored diff if possible
// Ignore whitespace and tab changes
// Ignore blank lines
// Don't print line directives in the diff when they would end up being alone in a fragment
// Label the original file without timestamp for reproducibility
// Label the modified file without timestamp for reproducibility

// Differences were found, thanks sherlock.

// Packages returns an iterator over the unique package names found in the report.
// It extracts the package names from the file paths, assuming they follow the convention of being
// constructed as "<work-dir>/orchestrion/src/<github.com/my/repo>/<file.go>".
func (r Report) Packages() []string { _ = "STUB: not implemented"; return nil }

// Files returns an iterator over the modified files in the report.
func (r Report) Files() []ModifiedFile { _ = "STUB: not implemented"; return nil }

// IsEmpty checks if the report contains no modified files.
func (r Report) IsEmpty() bool { _ = "STUB: not implemented"; return false }
